name: Release

on:
  push:
    branches:
      - release

permissions:
  contents: write

jobs:
  release:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install dependencies
        run: npm ci

      - name: Get version from package.json
        id: package-version
        shell: bash
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Build Tauri app
        run: npm run tauri build

      - name: Check if executable exists (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          if (-not (Test-Path "./src-tauri/target/release/bc.exe")) {
            Write-Error "Build failed: bc.exe not found"
            exit 1
          }
          Write-Host "Build successful: bc.exe found"

      - name: Check if executable exists (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          if [ ! -f "./src-tauri/target/release/bc" ]; then
            echo "Build failed: bc not found"
            exit 1
          fi
          echo "Build successful: bc found"

      - name: Upload Windows artifact
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: bc-windows
          path: ./src-tauri/target/release/bc.exe

      - name: List macOS build outputs
        if: matrix.os == 'macos-latest'
        run: |
          echo "=== Bundle directory structure ==="
          find ./src-tauri/target/release/bundle -type f -name "*.dmg" -o -name "*.app" | head -20
          
      - name: Upload macOS artifact
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: bc-macos
          path: ./src-tauri/target/release/bundle/dmg/*.dmg

  create-release:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version from package.json
        id: package-version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Get PR body
        id: pr-body
        shell: bash
        run: |
          # Install GitHub CLI if not available
          if ! command -v gh &> /dev/null; then
            echo "Installing GitHub CLI..."
            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
            sudo apt update
            sudo apt install gh -y
          fi
          
          # Get the most recent merged PR to release branch
          PR_NUMBER=$(gh pr list --base release --state merged --limit 1 --json number -q '.[0].number')
          
          if [ -z "$PR_NUMBER" ]; then
            echo "No merged PR found"
            echo "PR_BODY=Release v${{ steps.package-version.outputs.VERSION }}" >> $GITHUB_OUTPUT
          else
            # Get PR body
            PR_BODY=$(gh pr view $PR_NUMBER --json body -q .body)
            echo "PR_BODY<<EOF" >> $GITHUB_OUTPUT
            echo "$PR_BODY" >> $GITHUB_OUTPUT
            echo "" >> $GITHUB_OUTPUT
            echo "---" >> $GITHUB_OUTPUT
            echo "SHA: ${{ github.sha }}" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Rename artifacts
        run: |
          # Debug: List downloaded artifact structure
          echo "=== Artifact structure ==="
          ls -la
          echo "=== bc-windows contents ==="
          ls -la ./bc-windows/ || echo "bc-windows directory not found"
          echo "=== bc-macos contents ==="
          ls -la ./bc-macos/ || echo "bc-macos directory not found"
          
          # Rename Windows artifact
          if [ -f "./bc-windows/bc.exe" ]; then
            mv ./bc-windows/bc.exe ./bc-v${{ steps.package-version.outputs.VERSION }}-windows-x64.exe
          else
            echo "Error: Windows executable not found"
            exit 1
          fi
          
          # Find and rename macOS DMG
          # The DMG should be directly in bc-macos directory after download
          DMG_FILE=$(find ./bc-macos -name "*.dmg" -type f 2>/dev/null | head -1)
          if [ -n "$DMG_FILE" ]; then
            echo "Found DMG: $DMG_FILE"
            mv "$DMG_FILE" ./bc-v${{ steps.package-version.outputs.VERSION }}-macos.dmg
          else
            echo "Warning: No DMG file found in bc-macos directory"
            echo "Contents of bc-macos:"
            find ./bc-macos -type f 2>/dev/null || echo "bc-macos directory is empty or doesn't exist"
          fi

      - name: Prepare artifact list
        id: artifacts
        run: |
          # Build artifact list
          ARTIFACTS=""
          
          # Add Windows artifact if it exists
          if [ -f "./bc-v${{ steps.package-version.outputs.VERSION }}-windows-x64.exe" ]; then
            ARTIFACTS="./bc-v${{ steps.package-version.outputs.VERSION }}-windows-x64.exe"
          fi
          
          # Add macOS artifact if it exists
          if [ -f "./bc-v${{ steps.package-version.outputs.VERSION }}-macos.dmg" ]; then
            if [ -n "$ARTIFACTS" ]; then
              ARTIFACTS="$ARTIFACTS,./bc-v${{ steps.package-version.outputs.VERSION }}-macos.dmg"
            else
              ARTIFACTS="./bc-v${{ steps.package-version.outputs.VERSION }}-macos.dmg"
            fi
          fi
          
          # Ensure we have at least one artifact
          if [ -z "$ARTIFACTS" ]; then
            echo "Error: No artifacts found to upload"
            exit 1
          fi
          
          echo "ARTIFACTS=$ARTIFACTS" >> $GITHUB_OUTPUT
          echo "Artifacts to upload: $ARTIFACTS"
          
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ steps.artifacts.outputs.ARTIFACTS }}
          artifactErrorsFailBuild: false
          tag: v${{ steps.package-version.outputs.VERSION }}
          name: BC App v${{ steps.package-version.outputs.VERSION }}
          body: ${{ steps.pr-body.outputs.PR_BODY }}
          allowUpdates: true
          skipIfReleaseExists: true
          token: ${{ secrets.GITHUB_TOKEN }}