name: Release

on:
  push:
    branches:
      - release

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install dependencies
        run: npm ci

      - name: Get version from package.json
        id: package-version
        run: |
          $version = (Get-Content package.json | ConvertFrom-Json).version
          echo "VERSION=$version" >> $env:GITHUB_OUTPUT

      - name: Build Tauri app
        run: npm run tauri build -- --no-bundle

      - name: Check if executable exists
        run: |
          if (-not (Test-Path "./src-tauri/target/release/bc.exe")) {
            Write-Error "Build failed: bc.exe not found"
            exit 1
          }
          Write-Host "Build successful: bc.exe found"

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./src-tauri/target/release/bc.exe"
          artifactErrorsFailBuild: true
          tag: v${{ steps.package-version.outputs.VERSION }}
          name: BC App v${{ steps.package-version.outputs.VERSION }}
          body: |
            Release v${{ steps.package-version.outputs.VERSION }}
            
            Download `bc.exe` from the assets below.
            
            SHA: ${{ github.sha }}
          allowUpdates: true
          skipIfReleaseExists: true
          token: ${{ secrets.GITHUB_TOKEN }}